sudo: required

services: 
  - docker

before_install:
  - docker build -t silviog1990/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true silviog1990/react-test npm test

after_success:
  - docker build -t silviog1990/multi-nginx ./nginx
  - docker build -t silviog1990/multi-client ./client
  - docker build -t silviog1990/multi-server ./server
  - docker build -t silviog1990/multi-worker ./worker
  # login into dockerhub
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "DOCKERHUB_ID" --password-stdin
  - docker push silviog1990/multi-nginx 
  - docker push silviog1990/multi-client
  - docker push silviog1990/multi-server
  - docker push silviog1990/multi-worker