sudo: required

services: 
  - docker

before_install:
  - docker build -t silviog1990/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true silviog1990/react-test npm test